export default [
  {
    id: '1',
    title: '表格组件',
    enTitle: 'TableComponent',
    path: '/table',
    permission: 'table:root',
    icon: 'svg-config',
    visible: true,
    keepAlive: true,
    status: 1,
    idx: 1,
    type: 0,
    children: [
      {
        id: '1-1',
        title: '超级表格',
        enTitle: 'ProTable',
        path: 'pro-table',
        permission: 'table:pro-table',
        icon: 'svg-system',
        visible: true,
        keepAlive: true,
        status: 1,
        idx: 1,
        type: 1,
        children: [],
      },
      {
        id: '1-2',
        title: '筛选表格',
        enTitle: 'FilterTable',
        path: 'filter-table',
        permission: 'table:filter-table',
        icon: 'svg-system',
        visible: true,
        keepAlive: true,
        status: 1,
        idx: 2,
        type: 1,
        children: [],
      },
    ],
  },
  {
    id: '2',
    title: '客服聊天',
    enTitle: 'ServiceChat',
    path: '/chat',
    permission: 'chat:root',
    icon: 'svg-config',
    visible: true,
    keepAlive: true,
    status: 1,
    idx: 2,
    type: 1,
    children: [],
  },
];
